#!/usr/bin/env python

import rospy
from geometry_msgs.msg import Twist
import sys, tty, termios, select
from std_msgs.msg import String

msg = """
Control Your TurtleBot3!
---------------------------
Moving around:
   q    w    e
   a    s    d
      space

CTRL-C to quit
"""

e = """
Communications Failed
"""

def talker():
    pub=rospy.Publisher('chatter', String, queue_size=10)
    rospy.init_node('talker', anonymous=True)
    rate= rospy.Rate(1)
    while not rospy.is_shutdown():
        hello_str= "1" #rospy.get_time()
        rospy.loginfo(hello_str)
        pub.publish(hello_str)
        rate.sleep()

def getKey():
    tty.setraw(sys.stdin.fileno())
    rlist, _, _ = select.select([sys.stdin], [], [], 0.1)
    if rlist:
        key = sys.stdin.read(1)
    else:
        key = ''

    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
    return key

if __name__ == '__main__':
    settings = termios.tcgetattr(sys.stdin)
    try:
        rospy.init_node('talker', anonymous=True)
        pub=rospy.Publisher('chatter', String, queue_size=10)
        status=0
        print(msg)
        while not rospy.is_shutdown():
            key = getKey()
            num=0
            if key == 'w' :
                status = status + 1
                num+=1
                rospy.loginfo(f"{key}, {num}")

            elif key == 's' :
                status = status + 1
                num+=2
                rospy.loginfo(f"{key}, {num}")

            elif key == 'a' :
                status = status + 1
                num+=4
                rospy.loginfo(f"{key}, {num}")

            elif key == 'd' :
                status = status + 1
                num+=8
                rospy.loginfo(f"{key}, {num}")

            elif key == 'q':
                num+=16
                status = status + 1
                rospy.loginfo(f"{key}, {num}")
            
            elif key == 'e':
                num+=32
                status = status + 1
                rospy.loginfo(f"{key}, {num}")

            elif key == 'Space':   
                num+=64
                status = status + 1
                rospy.loginfo(f"{key}, {num}")

            else:
                if (key == '\x03'):
                    break

            if status == 20 :
                print(msg)
                status = 0

            pub.publish(num)

    except rospy.ROSInterruptException:
        print(e)
    
    finally:
        num = 0
        pub.publish(num)

    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)